apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: databases
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/andsus/devops-labs.git
        revision: main
        directories:
          - path: 90-n8n/databases/*/overlays/*
  template:
    metadata:
      name: '{{ index .path.segments 2 }}-db-{{ index .path.segments 4 }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/andsus/devops-labs.git
        targetRevision: main
        path: '{{ .path.path }}'   # ‚Üê use the full path provided by the generator
      destination:
        server: https://kubernetes.default.svc
        namespace: 'cnpg-{{ index .path.segments 4 }}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
